- hosts: cloudafrica
  sudo: true

  tasks:
    - name: Install Apache and Deps
      apt: name={{ item }} update_cache=yes
      with_items:
        - apache2
        - python-software-properties

    - name: Ensure apache2 starts at boot
      service: name=apache2 state=started enabled=yes

    - name: Copy test.php file
      copy: src=test.php dest=/var/www/html/

    - name: Add ppa:ondrej/php5-5.6
      apt_repository: repo='ppa:ondrej/php5-5.6'

    - name: Resync apt and upgrade deps 
      apt: update_cache=yes

    - name: Install php5
      apt: name=php5
      register: php5_install

    #- debug: var=php5_install

    - name: Conditionally restart apache
      service: name=apache2 state=restarted
      when: php5_install.changed 

    - debug: msg="Host address is http://{{ ansible_eth0.ipv4.address }}/"
