- name: Add ppa:ondrej/php5-5.6
  apt_repository: repo='ppa:ondrej/php5-5.6'

- name: Resync apt and upgrade deps
  apt: update_cache=yes

- name: Install php5
  apt: name=php5
  register: php5_install

#- debug: var=php5_install

- name: Conditionally restart apache
  service: name=apache2 state=restarted
  when: php5_install.changed
