- hosts: cloudafrica
  sudo: true

  roles:
    - { role: common, tags: common }
    - { role: apache, tags: install.apache }
    - { role: php,    tags: install.php }
    - { role: mysql,  tags: install.mysql }

  tasks:

    - name: Copy test.php file
      copy: src=test.php dest=/var/www/html/
      tags: copy.test

    - debug: msg="Host address is http://{{ ansible_eth0.ipv4.address }}/"
      tags: debug
